### ISSUE TITLE
Tool relies on attendance tool table

### ISSUE THREAD

**Issue by davidpbauer** [tsugitools/ckpaper#1]
https://github.com/tsugitools/ckpaper/blob/6edec8f5d93de406fc63b78576976d058bf5df67/edit.php#L28

Installed this locally and it doesn't work because we don't have the attendance tool in our instance. It looks like this isn't actually needed. Can I remove?

**Comment by csev** [comment]
Woah - that is bad code from a copy/paste - it needs to be removed - this has nothing to do with the attendance tool.   

Please remove it.

/Chuck

**Comment by davidpbauer** [comment]
Removed and working now.
